- hosts: all
  gather_facts: no
  sudo: true

  tasks:

    - name: kill party process
      shell: "kill $(pgrep -f reliable)"
      ignore_errors: yes

# sysctl -w net.ipv4.udp_mem='4096 87380 8388608'
# sysctl -w net.ipv4.udp_mem='764913	1019887	1529826'

    - name: configure udp params
      shell: sysctl -w net.core.wmem_default=65536 && sysctl -w net.core.wmem_max=1677216 && \
        sysctl -w net.core.rmem_default=8388608 && sysctl -w net.core.rmem_max=1677216 && \
        sysctl -w net.ipv4.udp_mem='4096 1019887 8388608' && sysctl -w net.ipv4.route.flush=1 && \
        sysctl -w net.core.netdev_max_backlog=2000 && sysctl -w net.core.netdev_budget=600

    - git:
        repo: 'https://github.com/GalacticExchange/reliable_broadcast.git'
        dest: /home/ubuntu/reliable_broadcast
        version: multihost_test

    - name: mvn clean install
      shell: "mvn clean install"
      args:
        chdir: /home/ubuntu/reliable_broadcast


    - name: run party
      shell: "nohup java -jar target/reliable_broadcast-1.0-SNAPSHOT.jar -b reliable -c config.yml -p > /tmp/party_log &"
      args:
        chdir: /home/ubuntu/reliable_broadcast

