// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/FramePacket.proto

package udp;

public final class FramePacketProto {
  private FramePacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:udp.Frame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required fixed32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required fixed32 index = 2;</code>
     */
    boolean hasIndex();
    /**
     * <code>required fixed32 index = 2;</code>
     */
    int getIndex();

    /**
     * <code>required fixed32 amount = 3;</code>
     */
    boolean hasAmount();
    /**
     * <code>required fixed32 amount = 3;</code>
     */
    int getAmount();

    /**
     * <code>required fixed32 lengthTotal = 4;</code>
     */
    boolean hasLengthTotal();
    /**
     * <code>required fixed32 lengthTotal = 4;</code>
     */
    int getLengthTotal();

    /**
     * <code>required bytes command = 5;</code>
     */
    boolean hasCommand();
    /**
     * <code>required bytes command = 5;</code>
     */
    com.google.protobuf.ByteString getCommand();

    /**
     * <code>required bytes nonce = 6;</code>
     */
    boolean hasNonce();
    /**
     * <code>required bytes nonce = 6;</code>
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <code>required bytes data = 7;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 7;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code udp.Frame}
   */
  public  static final class Frame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:udp.Frame)
      FrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Frame.newBuilder() to construct.
    private Frame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Frame() {
      version_ = 0;
      index_ = 0;
      amount_ = 0;
      lengthTotal_ = 0;
      command_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Frame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              version_ = input.readFixed32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              index_ = input.readFixed32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              amount_ = input.readFixed32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              lengthTotal_ = input.readFixed32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              command_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              nonce_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return udp.FramePacketProto.internal_static_udp_Frame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return udp.FramePacketProto.internal_static_udp_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              udp.FramePacketProto.Frame.class, udp.FramePacketProto.Frame.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required fixed32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private int index_;
    /**
     * <code>required fixed32 index = 2;</code>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed32 index = 2;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_;
    /**
     * <code>required fixed32 amount = 3;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required fixed32 amount = 3;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int LENGTHTOTAL_FIELD_NUMBER = 4;
    private int lengthTotal_;
    /**
     * <code>required fixed32 lengthTotal = 4;</code>
     */
    public boolean hasLengthTotal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required fixed32 lengthTotal = 4;</code>
     */
    public int getLengthTotal() {
      return lengthTotal_;
    }

    public static final int COMMAND_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString command_;
    /**
     * <code>required bytes command = 5;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes command = 5;</code>
     */
    public com.google.protobuf.ByteString getCommand() {
      return command_;
    }

    public static final int NONCE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <code>required bytes nonce = 6;</code>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes nonce = 6;</code>
     */
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 7;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required bytes data = 7;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLengthTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNonce()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, index_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed32(3, amount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed32(4, lengthTotal_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, command_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, nonce_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, index_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, amount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, lengthTotal_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, command_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, nonce_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof udp.FramePacketProto.Frame)) {
        return super.equals(obj);
      }
      udp.FramePacketProto.Frame other = (udp.FramePacketProto.Frame) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasIndex() == other.hasIndex());
      if (hasIndex()) {
        result = result && (getIndex()
            == other.getIndex());
      }
      result = result && (hasAmount() == other.hasAmount());
      if (hasAmount()) {
        result = result && (getAmount()
            == other.getAmount());
      }
      result = result && (hasLengthTotal() == other.hasLengthTotal());
      if (hasLengthTotal()) {
        result = result && (getLengthTotal()
            == other.getLengthTotal());
      }
      result = result && (hasCommand() == other.hasCommand());
      if (hasCommand()) {
        result = result && getCommand()
            .equals(other.getCommand());
      }
      result = result && (hasNonce() == other.hasNonce());
      if (hasNonce()) {
        result = result && getNonce()
            .equals(other.getNonce());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasIndex()) {
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndex();
      }
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount();
      }
      if (hasLengthTotal()) {
        hash = (37 * hash) + LENGTHTOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getLengthTotal();
      }
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand().hashCode();
      }
      if (hasNonce()) {
        hash = (37 * hash) + NONCE_FIELD_NUMBER;
        hash = (53 * hash) + getNonce().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static udp.FramePacketProto.Frame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udp.FramePacketProto.Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udp.FramePacketProto.Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static udp.FramePacketProto.Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static udp.FramePacketProto.Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udp.FramePacketProto.Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(udp.FramePacketProto.Frame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code udp.Frame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:udp.Frame)
        udp.FramePacketProto.FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return udp.FramePacketProto.internal_static_udp_Frame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return udp.FramePacketProto.internal_static_udp_Frame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                udp.FramePacketProto.Frame.class, udp.FramePacketProto.Frame.Builder.class);
      }

      // Construct using udp.FramePacketProto.Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lengthTotal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        command_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        nonce_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return udp.FramePacketProto.internal_static_udp_Frame_descriptor;
      }

      public udp.FramePacketProto.Frame getDefaultInstanceForType() {
        return udp.FramePacketProto.Frame.getDefaultInstance();
      }

      public udp.FramePacketProto.Frame build() {
        udp.FramePacketProto.Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public udp.FramePacketProto.Frame buildPartial() {
        udp.FramePacketProto.Frame result = new udp.FramePacketProto.Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lengthTotal_ = lengthTotal_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.nonce_ = nonce_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof udp.FramePacketProto.Frame) {
          return mergeFrom((udp.FramePacketProto.Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(udp.FramePacketProto.Frame other) {
        if (other == udp.FramePacketProto.Frame.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasLengthTotal()) {
          setLengthTotal(other.getLengthTotal());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasIndex()) {
          return false;
        }
        if (!hasAmount()) {
          return false;
        }
        if (!hasLengthTotal()) {
          return false;
        }
        if (!hasCommand()) {
          return false;
        }
        if (!hasNonce()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        udp.FramePacketProto.Frame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (udp.FramePacketProto.Frame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required fixed32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required fixed32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <code>required fixed32 index = 2;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed32 index = 2;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>required fixed32 index = 2;</code>
       */
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000002;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 index = 2;</code>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        index_ = 0;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>required fixed32 amount = 3;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required fixed32 amount = 3;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>required fixed32 amount = 3;</code>
       */
      public Builder setAmount(int value) {
        bitField0_ |= 0x00000004;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 amount = 3;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0;
        onChanged();
        return this;
      }

      private int lengthTotal_ ;
      /**
       * <code>required fixed32 lengthTotal = 4;</code>
       */
      public boolean hasLengthTotal() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required fixed32 lengthTotal = 4;</code>
       */
      public int getLengthTotal() {
        return lengthTotal_;
      }
      /**
       * <code>required fixed32 lengthTotal = 4;</code>
       */
      public Builder setLengthTotal(int value) {
        bitField0_ |= 0x00000008;
        lengthTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 lengthTotal = 4;</code>
       */
      public Builder clearLengthTotal() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lengthTotal_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString command_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes command = 5;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes command = 5;</code>
       */
      public com.google.protobuf.ByteString getCommand() {
        return command_;
      }
      /**
       * <code>required bytes command = 5;</code>
       */
      public Builder setCommand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes command = 5;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000010);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes nonce = 6;</code>
       */
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes nonce = 6;</code>
       */
      public com.google.protobuf.ByteString getNonce() {
        return nonce_;
      }
      /**
       * <code>required bytes nonce = 6;</code>
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes nonce = 6;</code>
       */
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000020);
        nonce_ = getDefaultInstance().getNonce();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 7;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bytes data = 7;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 7;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 7;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:udp.Frame)
    }

    // @@protoc_insertion_point(class_scope:udp.Frame)
    private static final udp.FramePacketProto.Frame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new udp.FramePacketProto.Frame();
    }

    public static udp.FramePacketProto.Frame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Frame>
        PARSER = new com.google.protobuf.AbstractParser<Frame>() {
      public Frame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Frame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Frame> getParserForType() {
      return PARSER;
    }

    public udp.FramePacketProto.Frame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GexMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:udp.GexMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated string signs = 2;</code>
     */
    java.util.List<java.lang.String>
        getSignsList();
    /**
     * <code>repeated string signs = 2;</code>
     */
    int getSignsCount();
    /**
     * <code>repeated string signs = 2;</code>
     */
    java.lang.String getSigns(int index);
    /**
     * <code>repeated string signs = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignsBytes(int index);
  }
  /**
   * Protobuf type {@code udp.GexMessage}
   */
  public  static final class GexMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:udp.GexMessage)
      GexMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GexMessage.newBuilder() to construct.
    private GexMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GexMessage() {
      message_ = "";
      signs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GexMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                signs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              signs_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          signs_ = signs_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return udp.FramePacketProto.internal_static_udp_GexMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return udp.FramePacketProto.internal_static_udp_GexMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              udp.FramePacketProto.GexMessage.class, udp.FramePacketProto.GexMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>required string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList signs_;
    /**
     * <code>repeated string signs = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSignsList() {
      return signs_;
    }
    /**
     * <code>repeated string signs = 2;</code>
     */
    public int getSignsCount() {
      return signs_.size();
    }
    /**
     * <code>repeated string signs = 2;</code>
     */
    public java.lang.String getSigns(int index) {
      return signs_.get(index);
    }
    /**
     * <code>repeated string signs = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignsBytes(int index) {
      return signs_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      for (int i = 0; i < signs_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, signs_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < signs_.size(); i++) {
          dataSize += computeStringSizeNoTag(signs_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSignsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof udp.FramePacketProto.GexMessage)) {
        return super.equals(obj);
      }
      udp.FramePacketProto.GexMessage other = (udp.FramePacketProto.GexMessage) obj;

      boolean result = true;
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && getSignsList()
          .equals(other.getSignsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (getSignsCount() > 0) {
        hash = (37 * hash) + SIGNS_FIELD_NUMBER;
        hash = (53 * hash) + getSignsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static udp.FramePacketProto.GexMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static udp.FramePacketProto.GexMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static udp.FramePacketProto.GexMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udp.FramePacketProto.GexMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(udp.FramePacketProto.GexMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code udp.GexMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:udp.GexMessage)
        udp.FramePacketProto.GexMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return udp.FramePacketProto.internal_static_udp_GexMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return udp.FramePacketProto.internal_static_udp_GexMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                udp.FramePacketProto.GexMessage.class, udp.FramePacketProto.GexMessage.Builder.class);
      }

      // Construct using udp.FramePacketProto.GexMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        signs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return udp.FramePacketProto.internal_static_udp_GexMessage_descriptor;
      }

      public udp.FramePacketProto.GexMessage getDefaultInstanceForType() {
        return udp.FramePacketProto.GexMessage.getDefaultInstance();
      }

      public udp.FramePacketProto.GexMessage build() {
        udp.FramePacketProto.GexMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public udp.FramePacketProto.GexMessage buildPartial() {
        udp.FramePacketProto.GexMessage result = new udp.FramePacketProto.GexMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          signs_ = signs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.signs_ = signs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof udp.FramePacketProto.GexMessage) {
          return mergeFrom((udp.FramePacketProto.GexMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(udp.FramePacketProto.GexMessage other) {
        if (other == udp.FramePacketProto.GexMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (!other.signs_.isEmpty()) {
          if (signs_.isEmpty()) {
            signs_ = other.signs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSignsIsMutable();
            signs_.addAll(other.signs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        udp.FramePacketProto.GexMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (udp.FramePacketProto.GexMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList signs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSignsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          signs_ = new com.google.protobuf.LazyStringArrayList(signs_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSignsList() {
        return signs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public int getSignsCount() {
        return signs_.size();
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public java.lang.String getSigns(int index) {
        return signs_.get(index);
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignsBytes(int index) {
        return signs_.getByteString(index);
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public Builder setSigns(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignsIsMutable();
        signs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public Builder addSigns(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignsIsMutable();
        signs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public Builder addAllSigns(
          java.lang.Iterable<java.lang.String> values) {
        ensureSignsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public Builder clearSigns() {
        signs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string signs = 2;</code>
       */
      public Builder addSignsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignsIsMutable();
        signs_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:udp.GexMessage)
    }

    // @@protoc_insertion_point(class_scope:udp.GexMessage)
    private static final udp.FramePacketProto.GexMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new udp.FramePacketProto.GexMessage();
    }

    public static udp.FramePacketProto.GexMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GexMessage>
        PARSER = new com.google.protobuf.AbstractParser<GexMessage>() {
      public GexMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GexMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GexMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GexMessage> getParserForType() {
      return PARSER;
    }

    public udp.FramePacketProto.GexMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_udp_Frame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_udp_Frame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_udp_GexMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_udp_GexMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protobuf/FramePacket.proto\022\003udp\"z\n\005Fra" +
      "me\022\017\n\007version\030\001 \002(\007\022\r\n\005index\030\002 \002(\007\022\016\n\006am" +
      "ount\030\003 \002(\007\022\023\n\013lengthTotal\030\004 \002(\007\022\017\n\007comma" +
      "nd\030\005 \002(\014\022\r\n\005nonce\030\006 \002(\014\022\014\n\004data\030\007 \002(\014\",\n" +
      "\nGexMessage\022\017\n\007message\030\001 \002(\t\022\r\n\005signs\030\002 " +
      "\003(\tB\027\n\003udpB\020FramePacketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_udp_Frame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_udp_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_udp_Frame_descriptor,
        new java.lang.String[] { "Version", "Index", "Amount", "LengthTotal", "Command", "Nonce", "Data", });
    internal_static_udp_GexMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_udp_GexMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_udp_GexMessage_descriptor,
        new java.lang.String[] { "Message", "Signs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
